name: super_app_behpardaz
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.3.2
  rxdart: ^0.28.0
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  fonts:
    - family: 'iransans_fa'
      fonts:
        - asset: assets/fonts/iransans_fa_black.ttf
          weight: 900
        - asset: assets/fonts/iransans_fa_bold.ttf
          weight: 700
        - asset: assets/fonts/iransans_fa_medium.ttf
          weight: 500
        - asset: assets/fonts/iransans_fa_regular.ttf
          weight: 400
        - asset: assets/fonts/iransans_fa_light.ttf
          weight: 300
        - asset: assets/fonts/iransans_fa_ultralight.ttf
          weight: 200